import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  loginscreen: {
    flex: 1,
    backgroundColor: "#fff",
  },
  whiteSheet: {
    width: "100%",
    height: "100%",
    position: "absolute",
    bottom: 0,
    backgroundColor: "#1B1B1B",
  },
  loginform: {
    flex: 1,
    justifyContent: "center",
    marginHorizontal: 30,
  },
  loginheading: {
    fontSize: 36,
    fontWeight: "bold",
    color: "white",
    alignSelf: "center",
    paddingBottom: 24,
  },
  logininputContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 5,
  },
  logininput: {
    backgroundColor: "#F6F7FB",
    height: 58,
    marginBottom: 20,
    fontSize: 16,
    borderRadius: 10,
    padding: 12,
  },
  loginbutton: {
    backgroundColor: "#2196f3",
    height: 58,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
  },
  loginbuttonText: {
    textAlign: "center",
    color: "#fff",
    fontWeight: "700",
    fontSize: 18,
  },
  chatscreen: {
    backgroundColor: "#1B1B1B",
    flex: 1,
    position: "relative",
  },
  chatheading: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
  },
  chattopContainer: {
    backgroundColor: "#111111",
    height: 70,
    width: "100%",
    padding: 20,
    justifyContent: "center",
    marginBottom: 15,
    elevation: 2,
    borderBottomWidth: 1,
    borderBottomColor: "darkgray",
  },
  chatheader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  chatlistContainer: {
    paddingHorizontal: 10,
  },
  chatemptyContainer: {
    width: "100%",
    height: "80%",
    alignItems: "center",
    justifyContent: "center",
  },
  chatemptyText: {
    fontWeight: "bold",
    fontSize: 24,
    paddingBottom: 30,
    color: "white",
  },
  messagingscreen: {
    flex: 1,
    backgroundColor: "#1B1B1B",
  },
  messaginginputContainer: {
    width: "100%",
    minHeight: 80,
    backgroundColor: "#111111",
    paddingVertical: 30,
    paddingHorizontal: 15,
    justifyContent: "center",
    flexDirection: "row",
  },
  messaginginput: {
    padding: 10,
    flex: 1,
    borderRadius: 10,
    backgroundColor: "#1B1B1B",
    color: "white",
  },
  messagingbuttonContainer: {
    position: "absolute",
    top: 38,
    right: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    padding: 2,
  },
  modalbutton: {
    width: "40%",
    height: 45,
    backgroundColor: "#2196f3",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
  },
  modalbuttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  modaltext: {
    color: "#fff",
  },
  modalContainer: {
    width: "100%",
    borderTopColor: "#ddd",
    borderTopWidth: 1,
    elevation: 1,
    height: 300,
    backgroundColor: "#111111",
    position: "absolute",
    bottom: 0,
    zIndex: 10,
    paddingVertical: 50,
    paddingHorizontal: 20,
  },
  modalinput: {
    borderWidth: 2,
    padding: 15,
  },
  modalsubheading: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
    color: "white",
  },
  mmessageWrapper: {
    width: "100%",
    alignItems: "flex-start",
    marginBottom: 15,
  },
  mmessage: {
    maxWidth: "60%",
    backgroundColor: "grey",
    padding: 15,
    borderRadius: 10,
    marginBottom: 2,
    color: "white",
  },
  mvatar: {
    marginRight: 5,
  },
  cchat: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 5,
    paddingHorizontal: 15,
    backgroundColor: "#fff",
    height: 80,
    marginBottom: 10,
  },
  cavatar: {
    marginRight: 15,
  },
  cusername: {
    fontSize: 18,
    marginBottom: 5,
    fontWeight: "bold",
  },
  cmessage: {
    fontSize: 14,
    opacity: 0.7,
  },
  crightContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    flex: 1,
  },
  ctime: {
    opacity: 0.5,
    color: "#565656",
  },
});
